version: '3.8'

services:
  ve-api-mysql:
    container_name: ve-api-mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ve-api-mysql
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - '3306:3306'
    networks:
      - ve-app-nw

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    networks:
      - ve-app-nw

networks:
  ve-app-nw:
    driver: bridge
    name: 've-app-nw'
